[package]
name = "bartender"
version = "0.1.0"
authors = ["Inokentiy Babushkin <inokentiy.babushkin@googlemail.com>"]
homepage = "https://ibabushkin.github.io/"
repository = "https://github.com/ibabushkin/bartender"
readme = "README.md"
license = "BSD3"

[dependencies]
config = "^0.1.3"
getopts = "^0.2.14"
libc = "^0.2.15"
